services:
  database:
    image: mariadb:latest
    container_name: fmevently-mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=root
      - MARIADB_USER=root
      - MARIADB_PASSWORD=root

    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mariadb_data: