spring:
  application:
    name: monolith
    namespace: live
  datasource:
    url: jdbc:mariadb://${DB_HOST_FAMEVENTLY}/famevently?autoReconnect=true&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-test-query: "SELECT NOW()"
      maximum-pool-size: 20
      minimum-idle: 8
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      default-ttl: P14D

  cache:
    type: redis

  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 5s
server:
  tomcat:
    mbeanregistry:
      enabled: true
  shutdown: graceful

services:
  user-sessions:
    base-url: http://api-gateway-service${suffix}
    create-session: ${services.user-sessions.base-url}/sessions/users/{userId}
    delete-session-by-device-uuid: ${services.user-sessions.base-url}/sessions/devices/{deviceUuid}
    validate-session: ${services.user-sessions.base-url}/sessions/{sessionId}
    read-timeout-in-millis: 3000
    connection-timeout-in-millis: 1000

suffix: ""

google:
  oauth2:
    client-id: 463363879926-8gdlvjqa7a9t13ct8olq646766l7959p.apps.googleusercontent.com
    secret: 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
