spring:
  application:
    name: monolith
    namespace: live

  datasource:
    url: jdbc:mariadb://localhost:3306/famevently
    username: root
    password: root
    hikari:
      connection-test-query: "SELECT NOW()"
      maximum-pool-size: 20
      minimum-idle: 8
      connection-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      url:
      timeout: PT2S # 2 seconds
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 5s